"use client";
import { useState } from "react";

const clients = [
  "7-Eleven",
  "99 Cent Only Stores",
  "A & R Wholesale Distributors",
  "A White and Yellow Cab Inc.",
  "Able Building Maintenance Co.",
  "Access Paratransit",
  "Agave Designs Inc.",
  "AJ Edmond Co., Inc.",
  "Aladin Hotel, Las Vegas",
  "Albertsons Markets",
  "Aliso Viejo Community Assoc.",
  "Alpha Beta Markets",
  "American Golf Corporation",
  "American Multi-Cinema, Inc.",
  "Ameriprise",
  "AMTRAK",
  "Andy Gump, Inc",
  "Antelope Valley Hospital",
  "Antelope Valley Schools Transportation Agency",
  "Anthony Pools",
  "Apple Annie's Restaurant & Bakery, Inc.",
  "Arbee Inc.",
  "Archdiocese of L.A.",
  "Arthur's Restaurant",
  "Ashley Furniture Industries, Inc.",
  "Athens Administrators",
  "Atlantic Express Transportation",
  "ATS Northeast Tow, Inc.",
  "Auto Technology Co.",
  "Axe Equipment",
  "B&H Education, Inc.",
  "Ballpark Pedicabs",
  "Bank of America",
  "Barnes & Noble, Inc.",
  "Barstow Community Hospital",
  "Barstow Fuel",
  "BassPro Shops",
  "BCI Coca-Cola Bottling Co.",
  "Beacon Capital Partners",
  "Bellagio Hotel, Las Vegas",
  "Berry Plastics Corp.",
  "Best Western Plus Hotel",
  "Beverly Alvarado Medical Bldg",
  "Beverly Hills School District",
  "Big Lots",
  "BJ's Restaurant",
  "Bldg Cleaning System",
  "Bonita U.S.D.",
  "Boys & Girls Club",
  "Boys Markets",
  "Bridgestone/Firestone Tires",
  "Bristol Farms",
  "Brookhurst Village HOA",
  "Builder’s Emporium",
  "Bundy Brentana HOA",
  "Burbank Glendale Pasadena Airport Authority",
  "C & H Plumbing",
  "California Cascade Industries",
  "California Land Industries",
  "California Steel Industries, Inc.",
  "Calloway",
  "CalTrans",
  "Calvary Chapel Conference Center",
  "Canyon Tile & Stone",
  "Cardenas Market",
  "Carl's Jr.",
  "Carlton Forge Works",
  "Carmel Village",
  "Carondelet Health",
  "Casa Escobar Westlake",
  "Caterpillar",
  "CDN Logistics Inc.",
  "Cedar Fair dba Knotts Berry Farm",
  "Cedars Medical Center",
  "Central Coast Playgrounds",
  "CFM Corporation",
  "Channel Islands HOA, CA",
  "Chapman Medical Center",
  "Charter Communications",
  "Chateau Lamont Apartments, Los Angeles",
  "Cheesecake Factory",
  "Ciao Bella Restaurant",
  "Cinemark USA Inc.",
  "Circus Circus Hotels, Las Vegas",
  "City of Alhambra, CA",
  "City of Azusa, CA",
  "City of Baldwin Park, CA",
  "City of Bellflower, CA",
  "City of Beverly Hills, CA",
  "City of Calabasas, CA",
  "City of Canyon Lakes, CA",
  "City of Diamond Bar, CA",
  "City of Hemet, CA",
  "City of Highland, CA",
  "City of La Habra, CA",
  "City of Lake Forest, CA",
  "City of Los Angeles, CA",
  "City of Madera, CA",
  "City of Mission Viejo, CA",
  "City of Newport Beach, CA",
  "City of Orange, CA",
  "City of Oxnard, CA",
  "City of Pasadena, CA",
  "City of Pico Rivera, CA",
  "City of Riverside, CA",
  "City of Rosemead, CA",
  "City of Santa Ana, CA",
  "City of Santa Clarita, CA",
  "City of Santa Monica, CA",
  "City of Torrance, CA",
  "City of Upland, CA",
  "Clark Forklifts",
  "Cliff Russell Construction",
  "Coach America",
  "Columbia Machine, Inc.",
  "Comfort Med Transport",
  "Consumer Product Safety Commission",
  "Cooper Tire",
  "Corona Park Apts, CA",
  "Corona Regional",
  "Corona Regional Medical Center",
  "Costco",
  "Country BBQ",
  "County of Los Angeles, CA",
  "County of Orange, CA",
  "County of Riverside, CA",
  "County of Ventura, CA",
  "Crawford and Co.",
  "Creekside Mobile Home Estates",
  "CSUN",
  "Curbside Inc.",
  "CVS Pharmacy, Inc.",
  "Daniels General Merchandise & Gifts",
  "Dat Moi Market",
  "Dave & Busters, Inc.",
  "D'Cache Restaurant",
  "De Anza Resort and Golf",
  "Dean Foods",
  "Decorator's Rug Warehouse, Inc.",
  "Deepz Investments Inc.",
  "Denny's",
  "Department of Energy, Washington D.C.",
  "Department of Interior, Washington D.C.",
  "Department of Justice, Washington D.C.",
  "Department of State, Washington D.C.",
  "Devonshire Silver Plaza, LLC",
  "Diamond Bar Golf Course, CA",
  "Didde Web Press",
  "Docor, Inc.",
  "Dollar Rent A Car",
  "Dorados Trucking",
  "Double Hi Express Tours",
  "Downey Regional Medical Ctr, CA",
  "Dream Castle LLC",
  "Dream World Limousine",
  "Driscoll's Strawberry Associates",
  "Drive Now",
  "Dronfield Estates Homeowners",
  "Drouin Realty, Inc.",
  "Eco-Tech of Kentucky",
  "Edge Property Mgmt Inc.",
  "El Dorado Car Wash",
  "El Jaguar Café & Grill",
  "El Jen Medical",
  "El Toro Market",
  "Encino Concord Tower, CA",
  "Encore Education Corp.",
  "Enterprise",
  "Enterprise Rent-A-Car Co.",
  "Environmental Cost Control",
  "Euclid Best Bargain, Inc.",
  "Euclid Mgmt Co.",
  "Excel Electric",
  "Expert Resources",
  "F. J. Willert Contracting Co., Inc.",
  "Farmer Boys Food, Inc.",
  "Farmer John",
  "Fatburger",
  "FedEx Ground",
  "Financial Indemnity",
  "First Transit",
  "Fitness International",
  "Foothill Transit",
  "Ford Contracting, Inc.",
  "Ford Motors Corporation",
  "Fort Wayne Pools",
  "Four Points Sheraton, CA",
  "Four Seasons, CA",
  "Fuddruckers",
  "G & K Management",
  "G E Venture LP",
  "Garfield Medical Center",
  "General Atomic Corporation",
  "General Motors",
  "George Jue Mfg. Co.",
  "Gerawan Farming Partners, Inc.",
  "GES Exposition Services",
  "Golden Valley Construction",
  "Golden West Arbor",
  "Goodyear",
  "Gordon Trucking",
  "GrayLift, Inc.",
  "Grosfillex",
  "Guardian Auto Repair",
  "Gulbranson Services",
  "Hahn Associates",
  "Harrington Industrial Plastics",
  "Harvester Trucks",
  "Heavy Hitters Music Group LLC",
  "Henry Mayo Newhall Mem Hosp",
  "Hertz Equipment Rental Corp",
  "Hilltop Schools, CA",
  "Hilton Hotels Corp.",
  "Hitachi Corporation",
  "Holiday Inn Corp.",
  "Hollywood Presbyterian Medical Ctr.",
  "Home Base",
  "Home Depot",
  "Hometown Buffet, Downey",
  "Honda Corporation",
  "Hope Chapel del Rey",
  "Horizon Fitness",
  "Hot Dogger Tours, Inc.",
  "House of Blues L.A. Corp.",
  "Hyundai Motors",
  "IDS Real Estate Group",
  "Idyllwild Arts Foundation",
  "Independent Taxi Owners Assoc of L.A.",
  "Inland Pipe Rehab",
  "Innovative Design Group",
  "Interco Tire Corp.",
  "Island Packers",
  "J.C. Produce",
  "Jack-In-The-Box",
  "Jacob’s Engineering",
  "James Real Estate Mgmt, Inc.",
  "James Restaurant",
  "Jet Propulsion Laboratory",
  "JFK Transportation",
  "JH Real Estate Partners, Inc.",
  "Jiffy Lube",
  "Joseph's Hospital",
  "JP Morgan Chase Bank",
  "Karls Toys",
  "Kearny Mesa Discovery, Inc.",
  "Keldon Paper Co.",
  "Kelly Fire Equipment",
  "Ken Grody Ford",
  "Kenworth Trucks",
  "Key Intl. Inc.",
  "Kimco Realty",
  "K-Mart",
  "KMK Management",
  "Kone Elevators & Escalators",
  "Korea Gardens Restaurant",
  "Ko's Merchant Centre",
  "Kozanian Ranch Market",
  "KP Properties",
  "Kroc Center",
  "KSL Resorts Corp.",
  "L.A. County Fire Dept., CA",
  "L.A. Hydro-Jet",
  "La Capilla Restaurant",
  "La Casa Garcia Restaurant",
  "La Costa Limousine",
  "La Rocque Better Roofs, Inc.",
  "LACMTA",
  "LaidLaw",
  "Lake Balboa Care Center",
  "Lake Perris Fairground",
  "Lakeshore Towers",
  "LAMTA",
  "Land Air Express",
  "Latino Center for Prevention and Action in Health & Welfare Inc.",
  "LAUSD",
  "LAX Beauty Ctr Inc.",
  "LifeHouse Cypress",
  "Lloyds of London",
  "Loew's Hotel",
  "Long Beach Care Center",
  "Long Beach Community Hospital, CA",
  "Los Alamitos Medical Center",
  "Los Angeles County Sheriff’s Department",
  "Los Angeles Dodgers, Inc.",
  "Los Robles Hospital & Medical Center",
  "Lucille’s Smokehouse Bar-B-Que",
  "Luxor Hotel",
  "M&N Rug Enterprises, LLC",
  "Mac Acquisition, LLC",
  "Mac's Delivery",
  "Malaga County Water District",
  "Manufacturers Bank",
  "Marie Calendars",
  "Marina Landscape",
  "Mark C. Bloom",
  "Marriott Hotel Services, Inc.",
  "Marriott Hotels, CA",
  "Mayfair Markets",
  "MCA",
  "McDonald's",
  "Merced County Transit, CA",
  "Mercedes of America",
  "Metropolitan Theatres Corp.",
  "MGM Grand Hotel International",
  "Milgard Mfg",
  "Miller Toyota of Anaheim, CA",
  "Minuteman Parking",
  "Mission LaRue Ltd Partnership",
  "Mission Linen",
  "Mitsubishi Corporation",
  "Mobil Oil",
  "Monarch",
  "Mountain Valley Express",
  "Mulhearn Realtors, RM3",
  "Muller Martini Mailroom Systems Inc.",
  "Munoz Contractors",
  "NASA, Washington D.C.",
  "National Presto Industries",
  "National Swimming Pool (Institute and Foundation)",
  "National Vision",
  "NBC",
  "New Castle Corp",
  "New City Auto",
  "Nippon Cargo Airlines",
  "Nissan Motors Co.",
  "NOAA, Washington D.C.",
  "Norms Restaurants",
  "Northstar Community Services District",
  "NU Concepts",
  "Nuclear Regulatory Commission, Washington D.C.",
  "NY NY Hotel, Las Vegas",
  "Oak Ridge National Laboratory, TN",
  "Okawa Sushi & Grill",
  "Olympia Medical Center",
  "One Baxter Way, LP",
  "Orange County Sheriff's Department",
  "Otis Elevator; Library Square",
  "Pacific Coast Foods, Inc.",
  "Pacific Coast Imaging",
  "Pacific Electric Lofts",
  "Pacifica Gardens Apts.",
  "Palm Desert Town Center, CA",
  "Paramount Villas LLC",
  "Parkwood Apts",
  "Partyworks Interactive",
  "Payless Drug Store",
  "Pep Boys",
  "Pertronix, Inc.",
  "Peterbuilt Trucks",
  "Petsmart",
  "Pho Thanh Restaurant",
  "Pic 'N' Save",
  "Pino Landscaping",
  "Portos Bakery",
  "Premier Carrier Inc",
  "Premier Food & Oils",
  "Presbyterian Intercommunity Hosp",
  "Prestige Service Inc.",
  "Primrose Villa, L.P.",
  "Providence Association",
  "Q & B Foods, Inc.",
  "Quail Ranch Golf Club",
  "Queen of Angels Hollywood Presbyterian Med Ctr",
  "Quest Diagnostics Clinical Laboratories, Inc.",
  "Radisson Hotels Corp.",
  "Rainbow Municipal Water District",
  "Raintree Apts",
  "Ralph’s Markets",
  "Ramona Care Center",
  "Rancho Vista Realty Inc.",
  "Raytheon",
  "Realtech Construction Co",
  "Redlands United Church of Christ",
  "Regal Theatres",
  "Regent Showcase Theatre",
  "Renegade Flooring",
  "Ricon Corporation",
  "Rite-Aid",
  "Ritz Carlton Hotels Corp.",
  "Riverside Community College District",
  "Rollins Trucking",
  "Rose Hills Memorial Park & Mortuary",
  "Ross Stores",
  "Rowland Heights Mobile Estates",
  "Royal Capital Seafood Restaurant",
  "Royal Logistics Inc",
  "RPL Transport Inc.",
  "RR Donnelley",
  "Rreef America LLC",
  "Ruan Logistics Corp",
  "Ruby's Diner",
  "Ryder Truck Rental",
  "S.A. Recycling",
  "Sam's Club",
  "San Antonio Community Hospital, TX",
  "San Bernardino Municipal Water Dept",
  "San Dimas Community Hospital, CA",
  "San Francisco Baseball Associates LLC",
  "San Francisco Giants Entities",
  "San Joaquin Community Hospital, CA",
  "Sandia National Laboratory, NM",
  "Santa Barbara Cottage Hospital, CA",
  "Santa Fe Railroad",
  "Savannah Chophouse Restaurant",
  "Save Mart Supermarkets",
  "Sav-on",
  "Scientific Technologies",
  "SDG&E",
  "Sea Esta Village, CA",
  "Sea Land Corporation",
  "Sea Ridge Condo Assoc",
  "See's Candies",
  "Select Personnel Services",
  "Select Staffing, ESIS",
  "Shilo Inns",
  "Shogun America, Inc.",
  "Shorehouse Café",
  "ShowFX Inc.",
  "Shuffle Master",
  "Shun Fat Supermarket",
  "Single Room Occupancy Housing Corp.",
  "Smart & Final Inc.",
  "Snow King",
  "SoCal Sanitation",
  "SoCal Wheels, Inc.",
  "Solar City",
  "South End Racquet & Health Club",
  "Southern California Edison",
  "Southwest Airlines",
  "Spitfire Grill",
  "Sportsmen’s Lodge",
  "Squires Lumber Co.",
  "St. Regis Resort",
  "Staples, Inc.",
  "Starbucks Corp.",
  "Sta-Rite Pools",
  "State of California, Attorney General's Office",
  "Steadfast Asset Management",
  "Sun City",
  "Sunshine Roofing",
  "Super Center Concepts",
  "Super King Market",
  "Superior Courts, Los Angeles",
  "Sureguard Security",
  "Swedish Performance",
  "Swift Transportation",
  "Swissport USA, Inc.",
  "Sword In The Stone",
  "Syroco",
  "Target Stores",
  "Temple Emmanuel Center",
  "Tender Greens",
  "Teramachi Seniors Housing",
  "Thanh Thanh Food To Go",
  "The Cookson Co., Inc.",
  "The Daily Grind",
  "The Hertz Corporation",
  "The Living Desert",
  "The Manhattan Strand Homes",
  "The National Orange Show",
  "The Oaks Camping Conference Center",
  "The Salvation Army",
  "The Three Sisters Truck Stop, Inc.",
  "Thrifty Payless",
  "Tommy Clothier",
  "Tommy's Hamburgers",
  "Torrance USD",
  "Toshiba Corporation",
  "Town of Apple Valley, CA",
  "Toys ‘R’ Us",
  "Trader Joes",
  "Troesh Readymix",
  "Tropicana Hotel, Las Vegas",
  "True Light Painting, Inc.",
  "Tuff Stuff Fitness Equipment, Inc.",
  "Twin Peaks",
  "U.S. Bank",
  "UCSD Regents",
  "United Auto Rental",
  "United El Segundo",
  "United States Elevator",
  "United States Government",
  "Universal Protection Service GP, Inc.",
  "University of Redlands",
  "Univision Communications",
  "Unocal Oil",
  "UPS",
  "US Air Force",
  "US Army",
  "US Navy",
  "Vadnais Corp.",
  "Vagabond Inn Corporation",
  "Valley Presbyterian Hospital",
  "Valleycrest Landscape Maintenance",
  "Ventura Port District",
  "Veolia Transportation Services",
  "Verano at Talega Homeowners Association",
  "Verizon CA Inc.",
  "Villa Angeles Apts.",
  "VIP Tours of California Inc.",
  "Virco Furniture",
  "Virco Mfg. Corp.",
  "Volcom Inc.",
  "Volvo-GM Corporation",
  "Von’s Markets",
  "Wabash National Corp.",
  "Walgreens",
  "Wal-Mart",
  "Waltco Truck Equipment Inc.",
  "Warner Center Condominiums",
  "Washington Mutual Bank",
  "West Kern Water District",
  "Westfield America Inc.",
  "Westfield Topanga",
  "Whittier Hospital Medical Center",
  "Whole Foods Market",
  "Wiggins Forklifts",
  "Wilshire Holmby HOA",
  "Wilshire Westholme Apts.",
  "Winn-Dixie Stores, Inc.",
  "Wolters Cluwer US Corp.",
  "Woodland Park Mobil Estates",
  "World Impact Inc.",
  "WSR Preservation Services, Inc.",
  "Young's Bargain Inc. dba Best Bargain",
  "YP Restaurant Group, Inc.",
  "Yum Yum Donut Shops Inc.",
  "Zepeda Construction",
  "Z-Gallerie",
];

const ITEMS_PER_PAGE = 15;

import { IoIosArrowBack } from "react-icons/io";
import { IoIosArrowForward } from "react-icons/io";

const ClientList = () => {
  const [page, setPage] = useState(1);

  const start = (page - 1) * ITEMS_PER_PAGE;
  const end = start + ITEMS_PER_PAGE;
  const paginatedClients = clients.slice(start, end);
  const totalPages = Math.ceil(clients.length / ITEMS_PER_PAGE);

  return (
    <div>
      <div className="flex items-center">
        <div className="flex items-center gap-5 border-2 rounded-xl px-5 py-1">
          <button
            onClick={() => setPage((p) => (p > 1 ? p - 1 : totalPages))}
            className="hover:text-[var(--primary)] transition-colors duration-200"
          >
            <IoIosArrowBack size={40} />
          </button>
          <p className="text-2xl">
            {page} / {totalPages}
          </p>
          <button
            onClick={() => setPage((p) => (p == totalPages ? 1 : p + 1))}
            className="hover:text-[var(--primary)] transition-colors duration-200"
          >
            <IoIosArrowForward size={40} />
          </button>
        </div>
      </div>

      <ul className="mt-5 flex flex-col gap-2">
        {paginatedClients.map((c) => (
          <li key={c}>
            <p className="text-xl">{c}</p>
            <div className="h-[2px] w-full bg-white"></div>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default ClientList;
